CRNGroupApp/Controllers/ShoppingListController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CRNGroupApp.Data;
using System;
using CRNGroupApp.Services;
using Microsoft.AspNet.Identity;
using PagedList;
using System.Xml.Linq;
using System.Web;
using System.Collections.Generic;

namespace CRNGroupApp.Controllers
{
    public class ShoppingListController : NameController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ShoppingListModel
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            var service = CreateListService();
            var model = service.GetLists();
            //var ctxdb = db.ShoppingLists
            //             .Where(e => e.UserId == Guid.Parse(User.Identity.GetUserId()));

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            if (searchString != null)
            {

                var shopinglistso = from s in db.ShoppingLists
                                    select s;
                //model = shopinglistso.Where(s => s.Name.Contains(searchString));
                model = model.Where(s => s.Name.Contains(searchString));
            }
            else
            {
                searchString = currentFilter;
            }

            //CHRIS: YOU MADE THIS C LOWER CASE DONT FORGET TO REVERT IF THAT DOESNT SOVLE THE ISSUE
            ViewBag.currentFilter = searchString;

            var shopinglists = from s in db.ShoppingLists
                               select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                shopinglists = shopinglists.Where(s => s.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    shopinglists = shopinglists.OrderByDescending(s => s.Name);
                    break;


                default:
                    shopinglists = shopinglists.OrderBy(s => s.Name);
                    break;
            }
            //var shoppingListItems = db.ShoppingListItems.Include(s => s.ShoppingList);


            return View(model.OrderBy(s => s.Name).ToPagedList(pageNumber, pageSize));
        }

        /* int pageSize = 3;
         int pageNumber = (page ?? 1);
         //var shoppingListItems = db.ShoppingListItems.Include(s => s.ShoppingList);
         return View(shopinglists.ToPagedList(pageNumber, pageSize));
     }*/

        // GET: ShoppingListModel/Details/5
        public ActionResult Details(int? id)
        {

            //replace with shoppinglistitem index
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShoppingListItem shoppingListItem = db.ShoppingListItems.Include(s => s.Files).SingleOrDefault(s => s.ShoppingListItemId == id);
            Data.ShoppingList shoppingListModel = db.ShoppingLists.Find(id);
            if (shoppingListModel == null)
            {
                return HttpNotFound();
            }

            //var i = new ShoppingListItem {ShoppingListId = id.Value};
            return View(shoppingListModel);
        }

        //adding ViewItem to ShoppingListController

        // GET: ViewItem/View
        public ActionResult ViewItem(int? id, string searchString)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.ShoppingListId = id;
            ViewBag.ListTitle = db.ShoppingLists.Find(id).Name;
            ViewBag.ShoppingListColor = db.ShoppingLists.Find(id).Color;
            if (!String.IsNullOrEmpty(searchString))
            {
                return View(db.ShoppingListItems.Where(s => s.Content.Contains(searchString)));
            }

            return View(db.ShoppingListItems.Where(s => s.ShoppingListId == id));

        }

        //POST: UpdateCheckBox
        [HttpPost]
        //[ValidateAntiForgeryToken]  //referencing id in order to update IsChecked,creating a new instance of class and calling it "shoppingListItem"
        public ActionResult UpdateCheckbox([Bind(Include = "ShoppingListItemId, IsChecked")] ShoppingListItem shoppingListItem)
        {   //pulling data from db and holding it in memory
            var item = db.ShoppingListItems.Find(shoppingListItem.ShoppingListItemId);
            //referencing IsChecked on item and converting it to IsChecked on shoppingListItem
            item.IsChecked = shoppingListItem.IsChecked;
            //Save changes
            db.SaveChanges();
            return Json("success");
        }



        // GET: ShoppingListItem/Create
        public ActionResult CreateItem(int? id)
        {
            ViewBag.ShoppingListId = id;
            ViewBag.ListTitle = db.ShoppingLists.Find(id).Name;
            return View();
        }

        // POST: ShoppingList/CreateItem
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateItem([Bind(Include = "ShoppingListItemId,ShoppingListId," +
                                                       "Content,Priority,Note,IsChecked,CreatedUtc,ModifiedUtc")]
                                                        ShoppingListItem shoppingListItem, int id, HttpPostedFileBase upload)
        {   //added parameter int id to "create".
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var avatar = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Avatar,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        avatar.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    shoppingListItem.Files = new List<File> { avatar };
                }

                //add shoppinglistitems to a particular list prior to "add"
                shoppingListItem.ShoppingListId = id;
                db.ShoppingListItems.Add(shoppingListItem);
                db.SaveChanges();
                return RedirectToAction("ViewItem", new { id });
            }
            //trying to return to view of shopping list items on a particular list
            return View();
        }


        // GET: ShoppingListModel/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ShoppingListModel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShoppingListId,UserId,Name,Color,CreatedUtc,ModifiedUtc")] Data.ShoppingList shoppingListModel)
        {
            if (ModelState.IsValid)
            {
                shoppingListModel.UserId = Guid.Parse(User.Identity.GetUserId());
                shoppingListModel.CreatedUtc = DateTimeOffset.Now;
                db.ShoppingLists.Add(shoppingListModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(shoppingListModel);
        }

        //copy and paste both create methods from shoppinglistitem to create a list item

        // GET: ShoppingListModel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShoppingListItem shoppingListItem = db.ShoppingListItems.Include(s => s.Files).SingleOrDefault(s => s.ShoppingListId == id);
            Data.ShoppingList shoppingListModel = db.ShoppingLists.Find(id);
            if (shoppingListModel == null)
            {
                return HttpNotFound();
            }
            return View(shoppingListModel);
        }

        // POST: ShoppingListModel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShoppingListId,UserId,Name,Color,CreatedUtc,ModifiedUtc")] Data.ShoppingList shoppingListModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(shoppingListModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(shoppingListModel);
        }

        // GET: ShoppingListModel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Data.ShoppingList shoppingListModel = db.ShoppingLists.Find(id);
            if (shoppingListModel == null)
            {
                return HttpNotFound();
            }
            return View(shoppingListModel);
        }

        // POST: ShoppingListModel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)

CRNGroupApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Never Forget</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container example5" style="width:100%;">
        <nav class="navbar navbar-default" style="width:auto; padding-top:0;">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar5">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="~/Home/Index">
                        <img style="	width: 64px;" src="~/Image/Floral-Pattern-Elephant-Silhouette-300px.png" alt="Never Forget">Never Forget Shopping List
                    </a>
                </div>
                <div id="navbar5" class="navbar-collapse collapse">
                    @Html.Partial("_LoginPartial")
                    <ul class="nav navbar-nav ">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Your Shopping Lists", "Index", "ShoppingList")</li>
                        }
                    </ul>

                </div>
                <!--/.nav-collapse -->
            </div>
            <!--/.container-fluid -->
        </nav>

    </div>

    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shopping List", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                    <li>@Html.ActionLink("Your Shopping Lists", "Index", "ShoppingList")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="text-align:center;">&copy; @DateTime.Now.Year - Never Forget Notes.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>